name: frog_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^2.19.3

dependencies:
  dart_frog: ^0.3.0
  envied: ^0.3.0+3
  http: ^0.13.6
  mongo_dart: ^0.9.1
  path: ^1.8.3

dev_dependencies:
  source_gen: ^1.2.3
  graphs: ^2.2.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0+3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
