openapi: '3.0.0'
info:
  version: 1.0.0
  title: Fun Facts
  description: Fun Facts API
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api/v1
paths:
  /fun/get-fact:
    $ref: './fun/get-fact/path.yaml'
  /fun/post-fact:
    $ref: './fun/post-fact/path.yaml'
  /fun/put-fact:
    $ref: './fun/put-fact/path.yaml'
  /fun/patch-fact:
    $ref: './fun/patch-fact/path.yaml'
  /fun/delete-fact:
    $ref: './fun/delete-fact/path.yaml'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key
